# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

require 'google/protobuf'

require 'context_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bosh.cpi_service.models.InfoRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
  end
  add_message "bosh.cpi_service.models.InfoResponse" do
    optional :stemcell_formats, :string, 1
  end
  add_message "bosh.cpi_service.models.CurrentVMIdRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
  end
  add_message "bosh.cpi_service.models.CurrentVMIdResponse" do
    optional :vm_cid, :string, 1
  end
end

module Bosh
  module CpiService
    module Models
      InfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.InfoRequest").msgclass
      InfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.InfoResponse").msgclass
      CurrentVMIdRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.CurrentVMIdRequest").msgclass
      CurrentVMIdResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.CurrentVMIdResponse").msgclass
    end
  end
end
