# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Bosh
  module CpiService
    module Models
    end
  end
end
