# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: context.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bosh.cpi_service.models.BoshContext" do
    optional :context_str, :string, 1
  end
end

module Bosh
  module CpiService
    module Models
      BoshContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.BoshContext").msgclass
    end
  end
end
