# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cpi_service.proto for package 'bosh.cpi_service.service'

require 'grpc'
require 'cpi_service_pb'

module Bosh
  module CpiService
    module Service
      module CPI
        # The cpi service definition.
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'bosh.cpi_service.service.CPI'

          rpc :Info, Bosh::CpiService::Models::InfoRequest, Bosh::CpiService::Models::InfoResponse
          # Create a stemcell
          rpc :CreateStemcell, Bosh::CpiService::Models::CreateStemcellRequest, Bosh::CpiService::Models::CreateStemcellResponse
          # Create a VM
          rpc :CreateVM, Bosh::CpiService::Models::CreateVMRequest, Bosh::CpiService::Models::CreateVMResponse
          rpc :DeleteVM, Bosh::CpiService::Models::DeleteVMRequest, Bosh::CpiService::Models::DeleteVMResponse
          rpc :HasVM, Bosh::CpiService::Models::HasVMRequest, Bosh::CpiService::Models::HasVMResponse
          rpc :RebootVM, Bosh::CpiService::Models::RebootVMRequest, Bosh::CpiService::Models::RebootVMResponse
          rpc :SetVMMetadata, Bosh::CpiService::Models::SetVMMetadataRequest, Bosh::CpiService::Models::SetVMMetadataResponse
          rpc :CreateDisk, Bosh::CpiService::Models::CreateDiskRequest, Bosh::CpiService::Models::CreateDiskResponse
          rpc :DeleteDisk, Bosh::CpiService::Models::DeleteDiskRequest, Bosh::CpiService::Models::DeleteDiskResponse
          rpc :ResizeDisk, Bosh::CpiService::Models::ResizeDiskRequest, Bosh::CpiService::Models::ResizeDiskResponse
          rpc :HasDisk, Bosh::CpiService::Models::HasDiskRequest, Bosh::CpiService::Models::HasDiskResponse
          rpc :AttachDisk, Bosh::CpiService::Models::AttachDiskRequest, Bosh::CpiService::Models::AttachDiskResponse
          rpc :DetachDisk, Bosh::CpiService::Models::DetachDiskRequest, Bosh::CpiService::Models::DetachDiskResponse
          rpc :SetDiskMetadata, Bosh::CpiService::Models::SetDiskMetadataRequest, Bosh::CpiService::Models::SetDiskMetadataResponse
          rpc :GetDisks, Bosh::CpiService::Models::GetDisksRequest, Bosh::CpiService::Models::GetDisksResponse
          rpc :SnapshotDisk, Bosh::CpiService::Models::SnapshotDiskRequest, Bosh::CpiService::Models::SnapshotDiskResponse
          rpc :DeleteSnapshot, Bosh::CpiService::Models::DeleteSnapshotRequest, Bosh::CpiService::Models::DeleteSnapshotResponse
          rpc :ConfigureNetworks, Bosh::CpiService::Models::ConfigureNetworksRequest, Bosh::CpiService::Models::ConfigureNetworksResponse
          rpc :CurrentVMId, Bosh::CpiService::Models::CurrentVMIdRequest, Bosh::CpiService::Models::CurrentVMIdResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
