# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cpi_service.proto

require 'google/protobuf'

require 'common_pb'
require 'disk_pb'
require 'network_pb'
require 'stemcell_pb'
require 'vm_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Bosh
  module CpiService
    module Service
    end
  end
end
