# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: disk.proto

require 'google/protobuf'

require 'context_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bosh.cpi_service.models.CreateDiskRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :size, :int64, 2
    optional :cloud_properties, :string, 3
    optional :vm_cid, :string, 4
  end
  add_message "bosh.cpi_service.models.CreateDiskResponse" do
    optional :disk_cid, :string, 1
  end
  add_message "bosh.cpi_service.models.DeleteDiskRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :disk_cid, :string, 2
  end
  add_message "bosh.cpi_service.models.DeleteDiskResponse" do
  end
  add_message "bosh.cpi_service.models.ResizeDiskRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :disk_cid, :string, 2
    optional :new_size, :int64, 3
  end
  add_message "bosh.cpi_service.models.ResizeDiskResponse" do
  end
  add_message "bosh.cpi_service.models.HasDiskRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :disk_cid, :string, 2
  end
  add_message "bosh.cpi_service.models.HasDiskResponse" do
    optional :exists, :bool, 1
  end
  add_message "bosh.cpi_service.models.AttachDiskRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :vm_cid, :string, 2
    optional :disk_cid, :string, 3
  end
  add_message "bosh.cpi_service.models.AttachDiskResponse" do
  end
  add_message "bosh.cpi_service.models.DetachDiskRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :vm_cid, :string, 2
    optional :disk_cid, :string, 3
  end
  add_message "bosh.cpi_service.models.DetachDiskResponse" do
  end
  add_message "bosh.cpi_service.models.SetDiskMetadataRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :disk_cid, :string, 2
    map :metadata, :string, :string, 3
  end
  add_message "bosh.cpi_service.models.SetDiskMetadataResponse" do
  end
  add_message "bosh.cpi_service.models.GetDisksRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :vm_cid, :string, 2
  end
  add_message "bosh.cpi_service.models.GetDisksResponse" do
    repeated :disk_cids, :string, 1
  end
  add_message "bosh.cpi_service.models.SnapshotDiskRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :disk_cid, :string, 2
    map :metadata, :string, :string, 3
  end
  add_message "bosh.cpi_service.models.SnapshotDiskResponse" do
    optional :snapshot_cid, :string, 1
  end
  add_message "bosh.cpi_service.models.DeleteSnapshotRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :snapshot_cid, :string, 2
  end
  add_message "bosh.cpi_service.models.DeleteSnapshotResponse" do
  end
end

module Bosh
  module CpiService
    module Models
      CreateDiskRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.CreateDiskRequest").msgclass
      CreateDiskResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.CreateDiskResponse").msgclass
      DeleteDiskRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DeleteDiskRequest").msgclass
      DeleteDiskResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DeleteDiskResponse").msgclass
      ResizeDiskRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.ResizeDiskRequest").msgclass
      ResizeDiskResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.ResizeDiskResponse").msgclass
      HasDiskRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.HasDiskRequest").msgclass
      HasDiskResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.HasDiskResponse").msgclass
      AttachDiskRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.AttachDiskRequest").msgclass
      AttachDiskResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.AttachDiskResponse").msgclass
      DetachDiskRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DetachDiskRequest").msgclass
      DetachDiskResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DetachDiskResponse").msgclass
      SetDiskMetadataRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.SetDiskMetadataRequest").msgclass
      SetDiskMetadataResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.SetDiskMetadataResponse").msgclass
      GetDisksRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.GetDisksRequest").msgclass
      GetDisksResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.GetDisksResponse").msgclass
      SnapshotDiskRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.SnapshotDiskRequest").msgclass
      SnapshotDiskResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.SnapshotDiskResponse").msgclass
      DeleteSnapshotRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DeleteSnapshotRequest").msgclass
      DeleteSnapshotResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DeleteSnapshotResponse").msgclass
    end
  end
end
