# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto

require 'google/protobuf'

require 'context_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bosh.cpi_service.models.ConfigureNetworksRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :vm_cid, :string, 2
    optional :networks, :string, 3
  end
  add_message "bosh.cpi_service.models.ConfigureNetworksResponse" do
  end
end

module Bosh
  module CpiService
    module Models
      ConfigureNetworksRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.ConfigureNetworksRequest").msgclass
      ConfigureNetworksResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.ConfigureNetworksResponse").msgclass
    end
  end
end
