# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stemcell.proto

require 'google/protobuf'

require 'context_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bosh.cpi_service.models.CreateStemcellRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :image_path, :string, 2
    optional :cloud_properties, :string, 3
  end
  add_message "bosh.cpi_service.models.CreateStemcellResponse" do
    optional :stemcell_cid, :string, 1
  end
  add_message "bosh.cpi_service.models.DeleteStemcellRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :stemcell_cid, :string, 2
  end
  add_message "bosh.cpi_service.models.DeleteStemcellResponse" do
  end
end

module Bosh
  module CpiService
    module Models
      CreateStemcellRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.CreateStemcellRequest").msgclass
      CreateStemcellResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.CreateStemcellResponse").msgclass
      DeleteStemcellRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DeleteStemcellRequest").msgclass
      DeleteStemcellResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DeleteStemcellResponse").msgclass
    end
  end
end
