# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm.proto

require 'google/protobuf'

require 'context_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bosh.cpi_service.models.CreateVMRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :agent_id, :string, 2
    optional :stemcell_cid, :string, 3
    repeated :disk_cids, :string, 4
    optional :cloud_properties, :string, 5
    optional :networks, :string, 6
    optional :environment, :string, 7
  end
  add_message "bosh.cpi_service.models.CreateVMResponse" do
    optional :vm_cid, :string, 1
  end
  add_message "bosh.cpi_service.models.HasVMRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :vm_cid, :string, 2
  end
  add_message "bosh.cpi_service.models.HasVMResponse" do
    optional :exists, :bool, 1
  end
  add_message "bosh.cpi_service.models.RebootVMRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :vm_cid, :string, 2
  end
  add_message "bosh.cpi_service.models.RebootVMResponse" do
  end
  add_message "bosh.cpi_service.models.SetVMMetadataRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :vm_cid, :string, 2
    map :metadata, :string, :string, 3
  end
  add_message "bosh.cpi_service.models.SetVMMetadataResponse" do
  end
  add_message "bosh.cpi_service.models.DeleteVMRequest" do
    optional :context, :message, 1, "bosh.cpi_service.models.BoshContext"
    optional :vm_cid, :string, 2
  end
  add_message "bosh.cpi_service.models.DeleteVMResponse" do
  end
end

module Bosh
  module CpiService
    module Models
      CreateVMRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.CreateVMRequest").msgclass
      CreateVMResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.CreateVMResponse").msgclass
      HasVMRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.HasVMRequest").msgclass
      HasVMResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.HasVMResponse").msgclass
      RebootVMRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.RebootVMRequest").msgclass
      RebootVMResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.RebootVMResponse").msgclass
      SetVMMetadataRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.SetVMMetadataRequest").msgclass
      SetVMMetadataResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.SetVMMetadataResponse").msgclass
      DeleteVMRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DeleteVMRequest").msgclass
      DeleteVMResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bosh.cpi_service.models.DeleteVMResponse").msgclass
    end
  end
end
