#!/bin/bash

set -ex

if [ -z ${TMPDIR+x} ]; then
  TMPDIR='/tmp'
fi

export BUNDLE_APP_CONFIG=$(mktemp -d $TMPDIR/bundler_config_XXXXXX)
export BUNDLE_CACHE_PATH="vendor/package"
export BUNDLE_WITHOUT="development:test"

bundle config specific_platform true
bundle lock --add-platform x86_64-linux
bundle lock --remove-platform x86_64-darwin-17
bundle package --all-platforms

rm -rf $BUNDLE_APP_CONFIG
